# Generated by Django 4.1.4 on 2024-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
