# Generated by Django 4.1.4 on 2024-07-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_loginrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='ip',
            field=models.CharField(max_length=32, verbose_name='登录ip'),
        ),
    ]
