# Generated by Django 4.1.4 on 2024-07-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.JSONField(blank=True, default=dict, help_text='柱状图', null=True, verbose_name='柱状图')),
                ('pie', models.JSONField(blank=True, default=dict, help_text='饼图', null=True, verbose_name='饼图')),
                ('line', models.JSONField(blank=True, default=dict, help_text='折线图', null=True, verbose_name='折线图')),
                ('scatter', models.JSONField(blank=True, default=dict, help_text='散点图', null=True, verbose_name='散点图')),
            ],
        ),
    ]
