# Generated by Django 4.1.4 on 2024-07-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='line',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='pie',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='scatter',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='图表'),
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.IntegerField(choices=[(1, '柱状图'), (2, '饼图')], default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
    ]
